version: "3.8"
services:
  whodb:
    image: clidey/whodb
    # volumes: # (optional for sqlite) 
    #   - ./sample.db:/db/sample.db
    environment:
#      optional if you have ollama configured elsewhere. will use these defaults otherwise
#      - WHODB_OLLAMA_HOST=localhost
#      - WHODB_OLLAMA_PORT=11434

#      use this to preconfigure your Anthropic connection. endpoint will default to below
      - WHODB_ANTHROPIC_API_KEY=...
#      - WHODB_ANTHROPIC_ENDPOINT=https://api.anthropic.com/v1

#     use this to preconfigure your OpenAI connection. endpoint will default to below
      - WHODB_OPENAI_API_KEY=...
#      - WHODB_OPENAI_ENDPOINT=https://api.openai.com/v1
    ports:
      - "18080:8080"