services:
  postgres:
    image: postgres:17.9
    container_name: postgres17
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - local_net
    restart: unless-stopped

networks:
  local_net:
    external: true

