version: '3.8'

services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - local_net
    restart: unless-stopped

networks:
  local_net:
    external: true

