version: '3.8'

services:
  redis:
    image: redis:7.4.1
    container_name: redis7
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - local_net
    restart: unless-stopped

networks:
  local_net:
    external: true
